# coding: utf-8

"""
    Project Peak API

    API for managing posts and categories on a website

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.category_api import router as CategoryApiRouter
from openapi_server.apis.post_api import router as PostApiRouter

app = FastAPI(
    title="Project Peak API",
    description="API for managing posts and categories on a website",
    version="1.1.0",
)

app.include_router(CategoryApiRouter)
app.include_router(PostApiRouter)
